### ISSUE TITLE
🐞 Flaky test in ./loader: TestInstance_String/multi_file

### ISSUE THREAD

**Issue by dolanor** [dagger/cuelsp#69]
### What is the issue?

The `TestInstance_String/multi_file` is flaky.

### Log output

```
--- FAIL: TestInstance_String (0.16s)
    --- FAIL: TestInstance_String/multi_file (0.16s)
        instance_test.go:157: 
            	Error Trace:	instance_test.go:157
            	Error:      	Not equal: 
            	            	expected: "Instance: action\nDefs:\n\t-\t#Action\n\t-\t#Plan\n"
            	            	actual  : "Instance: action\nDefs:\n\t-\t#Plan\n\t-\t#Action\n"
            	            	
            	            	Diff:
            	            	--- Expected
            	            	+++ Actual
            	            	@@ -2,4 +2,4 @@
            	            	 Defs:
            	            	+	-	#Plan
            	            	 	-	#Action
            	            	-	-	#Plan
            	            	 
            	Test:       	TestInstance_String/multi_file
FAIL
FAIL	github.com/dagger/daggerlsp/loader	0.931s

```

### Steps to reproduce

```
go test -count 1 -run TestInstance_String/multi_file ./loader
```

### Dagger version

daggerlsp v0.3.2

### OS version

Ubuntu 20.04

**Comment by dolanor** [comment]
@grouville : 
It seems it's only used by the flaky test. Is the `.String()` method useful somewhere else? Or is it mostly for debug?
If so, maybe we should just dump it, or make a `instanceString(i instance)` helper func.
Since the test is flaky, I'd rather we don't have it anymore. But since the method itself is not used as well, I'd rather we get rid of it?

**Comment by dolanor** [comment]
Seen with @grouville , we'll dump the method + the test.

**Comment by TomChv** [comment]
I think it's important to keep it but we can comment the test yes

**Comment by dolanor** [comment]
For me, it seems dead code as it is not used directly except by its test.
Is it used indirectly like with `fmt.Printf("%s", instanceI)`? If yes, then yes, we need to keep it.
We shouldn't comment the test though, we should remove it. If we want to get it back, it's in the git history.

**Comment by TomChv** [comment]
Yeah in debug mode we are often displaying `instance`.
However, I agree with you, we can easily remove the test for now
